# URL de conexión (fíjate que agregamos "jdbc:" al principio)
spring.datasource.url=jdbc:postgresql://ep-sweet-breeze-ag3dah0m-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require

# Credenciales
spring.datasource.username=neondb_owner
spring.datasource.password=npg_vq1XLhT6MFNi

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true