package com.monster_hunter.monster_hunter.freedom.materials.enums;

public enum Category {
    CATEGORY_CONSUMABLE_ITEMS, CATEGORY_GATHERING_TOOLS, CATEGORY_HUNTING_TOOLS, CATEGORY_SUPPLY_AND_ACCOUNT_ITEMS, CATEGORY_BOWGUN_AMMUNITION,
    CATEGORY_PLANTS_MUSHROOMS_AND_SEEDS, CATEGORY_MINERALS, CATEGORY_INSECTS, CATEGORY_MONSTER_SACS, CATEGORY_MONSTER_BONES, CATEGORY_MONSTER_MATERIALS
}
